[package]
name = "discord-rust"
version = "0.1.0"
authors = ["Denis <Zaratan> Pasin <zaratan@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.1"